.TH vbox 1 "March 2001" "ISDN 4 Linux @I4LVERSION@" ""

.SH NAME
vbox \- interact with recorded messages

.SH SYNOPSIS
.B vbox
.I [-f|--force] [-o|--mono] [-s|--noledstatus] [-c|--playcmd player] [-m|--hostname server] [-p|--port port] [-r |--reload SECS]
.I [-v|--version]
.I [-h|--help]

.SH DESCRIPTION
This is the program with which you can listen to recorded messages.

.SH SEE ALSO
.B autovbox(1), vboxtoau(1), vboxmode(1), vboxcnvt(1), vbox(5)

.SH AUTHOR
This manual page was written by Paul Slootman <paul@debian.org>,
for Debian GNU/Linux and isdn4linux.
