#! /bin/sh
##
## $Id: mkpos,v 1.2 1997/04/04 09:32:50 michael Exp $
##
## Script to create the misc message catalogs. This is only for development!

    # Get all sources (*.c) to a variable #

GETTEXT_SOURCE_FILES=""

for i in ${VBOX_TOPDIR}/src/*.c
do
    GETTEXT_SOURCE_FILES="${GETTEXT_SOURCE_FILES} ${i}"
done

    # Process each existing catalog #

for i in ${VBOX_CATALOGS}
do
    OLD_PO_FILE="${VBOX_TOPDIR}/messages/tmp-o-${i}"
    NEW_PO_FILE="${VBOX_TOPDIR}/messages/tmp-n-${i}"

    echo "Creating '${VBOX_TOPDIR}/messages/${i}.po'..."

    if (test -f ${VBOX_TOPDIR}/messages/${i}.po)
    then
	cp ${VBOX_TOPDIR}/messages/${i}.po ${VBOX_TOPDIR}/messages/backup-${i}.po
	mv ${VBOX_TOPDIR}/messages/${i}.po ${OLD_PO_FILE}.po
    fi

    xgettext --default-domain=${NEW_PO_FILE} \
	     --sort-output \
	     ${GETTEXT_SOURCE_FILES}

    if (test -f ${OLD_PO_FILE}.po)
    then
	tupdate ${NEW_PO_FILE}.po ${OLD_PO_FILE}.po >${VBOX_TOPDIR}/messages/${i}.po 2>/dev/null

	rm ${OLD_PO_FILE}.po ${NEW_PO_FILE}.po
    else
	mv ${NEW_PO_FILE}.po ${VBOX_TOPDIR}/messages/${i}.po
    fi

    echo "Creating '${VBOX_TOPDIR}/messages/${i}.mo'..."

    msgfmt --output-file=${VBOX_TOPDIR}/messages/${i}.mo ${VBOX_TOPDIR}/messages/${i}.po
done
