.\" $Id: $
.\"
.\" CHECKIN $Date: $
.\"
.\" Process this file with
.\" groff -man -Tascii divalog for ASCII output, or
.\" groff -man -Tps divalog for PostScript output
.\"
.TH DIVALOG 8 "2000/12/02" divalog "Linux System Administration"
.SH NAME
divalog \- Utility to read and translate messages from divalogd
.SH SYNOPSIS
divalog [-a N] [-z] [[-w] | [-f file] [-x] [-c] [-i]
.SH DESCRIPTION
.B divalog
is used to read and translate messages from divalogd.
.SH OPTIONS
.TP
.BI "-a" " N"
to specify adapter number (N defaults to 1)

.TP
.BI -z
to clear log of all entries

.TP
.BI -w
to wait for entries to be logged

.TP
.BI -f
file to log to specified file

.TP
.BI -x
read ISDN trace

.TP
.BI -c
read CAPI trace

.TP
.BI -i
read IDI trace

.SH AUTHOR
manpage written from usage output by Paul Slootman <paul@debian.org>.
